// electricalCommon.mjs — shared constants for the Electrical module.
//
// Every calculated protection value carries one of these four statuses,
// per the spec's explicit requirement never to present a calculated value
// as an approved field setting.
export const SETTING_STATUS = {
  CALCULATED: 'CALCULATED',     // pure mathematical result from entered data
  RECOMMENDED: 'RECOMMENDED',   // preliminary engineering setting from a stated philosophy/assumption
  USER_SELECTED: 'USER_SELECTED', // the value the engineer actually chose
  VERIFIED: 'VERIFIED',         // confirmed against manufacturer/system-study data
};

export const ENGINEERING_CHECK = { PASS: 'PASS', WARNING: 'WARNING', REVIEW_REQUIRED: 'REVIEW REQUIRED' };

export const PROTECTION_DISCLAIMER = 'Protection settings generated by this application are preliminary engineering calculations and recommendations. Final protection settings must be verified using actual system studies, equipment manufacturer data, relay characteristics, CT performance, fault levels, grounding arrangements, equipment withstand capabilities, protection philosophy, and applicable standards by a qualified electrical/protection engineer before implementation.';

export const GROUNDING_TYPES = ['solid', 'resistance', 'reactance', 'ungrounded'];

export function sqrt3() { return Math.sqrt(3); }
